### ISSUE TITLE
Overflow crash

### ISSUE THREAD

**Issue by fmorency** [Nemo157/cbor-diag-rs#113]
This issue can be reproduced ONLY when compiling the CLI in `Debug`; it does NOT occur when compiling the CLI in `Release`.

Run 
```
$ cargo build -p cbor-diag-cli
```

then run

```
$ echo a300470128bf0000002c01c11a62978f4d02a100820400 | ./target/debug/cbor-diag --to diag
thread 'main' panicked at 'attempt to subtract with overflow', src/encode/diag.rs:42:42
```

The CBOR diagnostic notation of the hex string is
```
{
    0: h'0128bf0000002c',
    1: 1(1654099789_2),
    2: {0: [4, 0]},
}
```

The crash occurs because the `len` variable is hardcoded to `4` and the `max` parameter given to the `estimate()` function is less than `4`, overflowing the unsigned subtraction `max - len`.

Thanks a lot for making and sharing this library!

**Comment by Nemo157** [comment]
Thanks for the report. The reason it only crashes in debug builds is that `-C overflow-checks` is only enabled by default in them (so in release it underflows and I think just wastes time estimating the length far in excess of the max allowed length, but still should behave correctly).

Looks like it should be a simple fix of switching to `saturating_sub` throughout the estimation code. I should be able to get that fixed tonight.
