### ISSUE TITLE
Update strum

### ISSUE THREAD

**Issue by Nemo157** [Nemo157/cbor-diag-rs#14]
Revert code changes from https://github.com/Nemo157/cbor-diag-rs/commit/77d606c961e505483989529e6ec52666b9af4ddf once strum 0.16 is released (hopefully soon https://github.com/Peternator7/strum/issues/69).

**Comment by Peternator7** [comment]
Version 0.16 is out! Let me know if you have any issues :)

**Comment by Nemo157** [comment]
Appears to be working perfectly, thanks!
